const mockTests = [
  {
    id: 'class-10',
    title: '10th Pass Govt Exam Mock',
    level: 'Class 10',
    description: 'Build a strong foundation with arithmetic, reasoning, general awareness and English.',
    duration: 20,
    difficulty: 'Foundation',
    questions: [
      { id: '10-1', section: 'Quantitative Aptitude', marks: 1, question_text: 'A shop gives a 10% discount on a shirt marked at ₹800. What is the sale price?', options: ['₹700', '₹720', '₹740', '₹760'], correct_option: 'b', explanation: '10% of ₹800 is ₹80. Sale price = ₹800 − ₹80 = ₹720.' },
      { id: '10-2', section: 'Quantitative Aptitude', marks: 1, question_text: 'The ratio of boys to girls in a class is 3:5. If there are 40 students, how many are boys?', options: ['15', '18', '20', '25'], correct_option: 'a', explanation: 'There are 3 + 5 = 8 equal parts. Each part is 40 ÷ 8 = 5, so boys = 3 × 5 = 15.' },
      { id: '10-3', section: 'Quantitative Aptitude', marks: 1, question_text: 'Solve: 4x − 7 = 21.', options: ['5', '6', '7', '8'], correct_option: 'c', explanation: 'Add 7 to both sides to get 4x = 28. Divide by 4: x = 7.' },
      { id: '10-4', section: 'Reasoning', marks: 1, question_text: 'Find the next number: 5, 10, 20, 40, __.', options: ['45', '60', '75', '80'], correct_option: 'd', explanation: 'Each term is doubled: 40 × 2 = 80.' },
      { id: '10-5', section: 'Reasoning', marks: 1, question_text: 'If EAST is coded as FBTU by shifting each letter forward by one, how is WEST coded?', options: ['XFTU', 'XFTV', 'VDRS', 'XEST'], correct_option: 'a', explanation: 'Move each letter forward once: W→X, E→F, S→T and T→U. The code is XFTU.' },
      { id: '10-6', section: 'General Awareness', marks: 1, question_text: 'Which is the supreme law of India?', options: ['The Parliament', 'The Constitution', 'The Supreme Court', 'The Cabinet'], correct_option: 'b', explanation: 'The Constitution of India is the supreme law and defines the framework of government.' },
      { id: '10-7', section: 'General Awareness', marks: 1, question_text: 'Which gas do plants primarily absorb during photosynthesis?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], correct_option: 'c', explanation: 'Plants use carbon dioxide and water to produce glucose and oxygen during photosynthesis.' },
      { id: '10-8', section: 'English', marks: 1, question_text: 'Choose the correctly spelled word.', options: ['Accomodation', 'Acommodation', 'Accommadation', 'Accommodation'], correct_option: 'd', explanation: 'The correct spelling is “accommodation,” with two c’s and two m’s.' },
    ],
  },
  {
    id: 'class-12',
    title: '12th Pass Govt Exam Mock',
    level: 'Class 12',
    description: 'Step up your preparation with algebra, data interpretation, reasoning and civics.',
    duration: 25,
    difficulty: 'Intermediate',
    questions: [
      { id: '12-1', section: 'Quantitative Aptitude', marks: 2, question_text: 'A sum of ₹5,000 earns simple interest at 8% per year for 2 years. What is the interest?', options: ['₹400', '₹600', '₹800', '₹1,000'], correct_option: 'c', explanation: 'Simple interest = P × R × T ÷ 100 = 5000 × 8 × 2 ÷ 100 = ₹800.' },
      { id: '12-2', section: 'Quantitative Aptitude', marks: 2, question_text: 'The average of 6 numbers is 18. If a seventh number, 25, is added, what is the new average?', options: ['18', '19', '20', '21'], correct_option: 'b', explanation: 'The original sum is 6 × 18 = 108. The new sum is 133, and 133 ÷ 7 = 19.' },
      { id: '12-3', section: 'Quantitative Aptitude', marks: 2, question_text: 'A train 180 m long travels at 54 km/h. How long does it take to pass a pole?', options: ['10 seconds', '12 seconds', '15 seconds', '18 seconds'], correct_option: 'b', explanation: '54 km/h = 15 m/s. Time = distance ÷ speed = 180 ÷ 15 = 12 seconds.' },
      { id: '12-4', section: 'Reasoning', marks: 2, question_text: 'Choose the pair that has the same relationship as Book : Read.', options: ['Food : Cook', 'Song : Listen', 'Pen : Write', 'Road : Walk'], correct_option: 'c', explanation: 'A book is used to read; similarly, a pen is used to write.' },
      { id: '12-5', section: 'Reasoning', marks: 2, question_text: 'A person faces north, turns right, then turns 180° left. Which direction are they facing?', options: ['North', 'South', 'East', 'West'], correct_option: 'd', explanation: 'Facing north, a right turn points east. Turning 180° from east points west.' },
      { id: '12-6', section: 'General Awareness', marks: 2, question_text: 'Which body conducts elections to the Parliament and state legislatures in India?', options: ['Union Public Service Commission', 'Election Commission of India', 'Finance Commission', 'NITI Aayog'], correct_option: 'b', explanation: 'The Election Commission of India supervises and conducts elections to Parliament and state legislatures.' },
      { id: '12-7', section: 'General Awareness', marks: 2, question_text: 'What is the SI unit of electric current?', options: ['Volt', 'Ohm', 'Watt', 'Ampere'], correct_option: 'd', explanation: 'Electric current is measured in amperes (A), named after André-Marie Ampère.' },
      { id: '12-8', section: 'English', marks: 2, question_text: 'Choose the grammatically correct sentence.', options: ['Neither of the answers are correct.', 'Neither of the answers is correct.', 'Neither answers is correct.', 'Neither of answers are correct.'], correct_option: 'b', explanation: '“Neither” is singular in this construction, so it takes the singular verb “is.”' },
    ],
  },
  {
    id: 'graduate',
    title: 'Graduate Level',
    level: 'Graduate',
    description: 'Challenge yourself with advanced aptitude, analytical reasoning and Indian polity.',
    duration: 30,
    difficulty: 'Advanced',
    questions: [
      { id: 'grad-1', section: 'Quantitative Aptitude', marks: 2, question_text: 'A can complete a job in 12 days and B in 18 days. Working together, how many days will they take?', options: ['6 days', '7.2 days', '8 days', '9 days'], correct_option: 'b', explanation: 'Their combined daily work is 1/12 + 1/18 = 5/36. Time = 36/5 = 7.2 days.' },
      { id: 'grad-2', section: 'Quantitative Aptitude', marks: 2, question_text: 'A value rises by 20% and then falls by 20%. What is the net change?', options: ['No change', 'A 2% decrease', 'A 4% decrease', 'A 4% increase'], correct_option: 'c', explanation: 'Using 100 as the starting value: 100 × 1.2 × 0.8 = 96, a net decrease of 4%.' },
      { id: 'grad-3', section: 'Quantitative Aptitude', marks: 2, question_text: 'The marked price of an item is ₹2,500. After a 10% discount, a 10% tax is applied to the discounted price. What is the final price?', options: ['₹2,475', '₹2,500', '₹2,525', '₹2,750'], correct_option: 'a', explanation: 'After discount: ₹2,500 × 0.9 = ₹2,250. Adding 10% tax gives ₹2,250 × 1.1 = ₹2,475.' },
      { id: 'grad-4', section: 'Reasoning', marks: 2, question_text: 'All analysts are graduates. Some graduates are writers. Which conclusion must follow?', options: ['All writers are analysts', 'Some analysts are writers', 'All analysts are graduates', 'No graduate is an analyst'], correct_option: 'c', explanation: 'The statement directly guarantees that all analysts belong to the group of graduates. It does not establish an overlap between analysts and writers.' },
      { id: 'grad-5', section: 'Reasoning', marks: 2, question_text: 'Find the next term: 3, 8, 18, 38, 78, __.', options: ['148', '156', '158', '160'], correct_option: 'c', explanation: 'Each term is the previous term multiplied by 2, then 2 is added: 78 × 2 + 2 = 158.' },
      { id: 'grad-6', section: 'General Awareness', marks: 2, question_text: 'A Money Bill can be introduced in which House of the Indian Parliament?', options: ['Lok Sabha only', 'Rajya Sabha only', 'Either House', 'A joint sitting only'], correct_option: 'a', explanation: 'A Money Bill can be introduced only in the Lok Sabha, on the President’s recommendation.' },
      { id: 'grad-7', section: 'General Awareness', marks: 2, question_text: 'Which constitutional article provides the Right to Equality?', options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'], correct_option: 'a', explanation: 'Article 14 of the Constitution guarantees equality before the law and equal protection of the laws.' },
      { id: 'grad-8', section: 'English', marks: 2, question_text: 'Choose the word closest in meaning to “pragmatic.”', options: ['Idealistic', 'Practical', 'Hesitant', 'Theoretical'], correct_option: 'b', explanation: '“Pragmatic” means dealing with matters in a practical, realistic way.' },
    ],
  },
  {
    id: 'ldce-asst-2024',
    title: 'LDCE Assistant 2024 Premium Practice',
    level: 'Graduate',
    description: 'Converted from the 2024 LDCE Assistant paper themes: government note drafting, cadre review proposal, UDISE+ analysis and precis writing.',
    duration: 45,
    difficulty: 'Advanced',
    is_free: false,
    bundle_id: 'f90e203c-5bb6-460f-989a-6f2d8ab103d6',
    questions: [
      { id: 'ldce-1', section: 'Noting & Drafting', marks: 2, question_text: 'Which of the following best captures the objective of a government note on school enrolment trends?', options: ['To highlight only the financial burden of schools', 'To review enrolment patterns and propose reforms for improving public school access', 'To replace all private schools with government schools', 'To restrict the publication of school-level data'], correct_option: 'b', explanation: 'A government note should analyze data, explain the reasons behind trends, and suggest practical measures to improve enrolment and service delivery.' },
      { id: 'ldce-2', section: 'Data Interpretation', marks: 2, question_text: 'According to the UDISE+ trend, which statement is most accurate?', options: ['Government school enrolment fell sharply in every category between 2019-20 and 2021-22', 'Government school enrolment showed an encouraging upward trend, especially at the primary and upper-primary levels', 'Private unaided schools saw a higher rate of growth than government schools in every segment', 'There was no significant change in enrolment patterns across school management types'], correct_option: 'b', explanation: 'The passage states that the data shows an encouraging trend in enrolment in government schools, especially when viewed across levels.' },
      { id: 'ldce-3', section: 'Policy Writing', marks: 2, question_text: 'A cadre review proposal should primarily focus on:', options: ['The personal preferences of senior officials only', 'Functional and structural adequacy, workload imbalance, stagnation, and efficiency concerns', 'Reducing all staffing levels without analysis', 'Replacing all clerical functions with automated systems immediately'], correct_option: 'b', explanation: 'The draft proposal should address functions, structural issues, workload distribution, and the need to improve efficiency and career progression.' },
      { id: 'ldce-4', section: 'Noting & Drafting', marks: 2, question_text: 'Which factor is most relevant when drafting a Government Order for a cadre review?', options: ['The committee composition and terms of reference', 'A random selection of personnel from one department only', 'Excluding workload analysis completely', 'Limiting the review to lower-level clerks only'], correct_option: 'a', explanation: 'A proper draft GO should define the review committee composition and specify the terms of reference and scope of work.' },
      { id: 'ldce-5', section: 'Precis Writing', marks: 2, question_text: 'The best précis of the Constitution passage would keep the emphasis on:', options: ['Only the historical development of the Constituent Assembly', 'The ideals of justice, liberty, equality, fraternity, and democratic governance', 'The administrative hierarchy of the civil services', 'The election process only'], correct_option: 'b', explanation: 'The passage highlights the Constitutional ideals, democratic values, and the role of institutions in improving the lives of citizens.' },
      { id: 'ldce-6', section: 'General Awareness', marks: 2, question_text: 'The phrase “Vishwa-Bandhu” in the source passage refers most closely to:', options: ['A focus on isolation from global ideas', 'India’s role as a friend of the world and a responsible international partner', 'A military alliance only', 'The role of the State in restricting public participation'], correct_option: 'b', explanation: 'The passage describes India as a “Vishwa-Bandhu,” meaning a friend of the world promoting peace and cooperation.' },
      { id: 'ldce-7', section: 'Writing Skills', marks: 2, question_text: 'When preparing a note to Government, the most effective opening is one that:', options: ['Begins with a detailed personal anecdote only', 'States the issue, context, evidence, and the proposed action clearly', 'Avoids any facts and uses only opinion', 'Lists only the names of departments involved'], correct_option: 'b', explanation: 'Government notes should be concise, evidence-based, and action-oriented, making the issue, analysis, and recommendation clear.' },
      { id: 'ldce-8', section: 'Policy & Governance', marks: 2, question_text: 'Which measure is most consistent with the spirit of the passage on constitutional ideals?', options: ['Reducing accountability to the judiciary', 'Promoting inclusion, welfare, justice and citizen participation', 'Restricting citizens to passive observation', 'Avoiding legislative reforms altogether'], correct_option: 'b', explanation: 'The passage argues that Constitutional ideals are strengthened when institutions and citizens work together to improve welfare, justice and inclusion.' },
    ],
  },
  {
    id: 'udc-2023',
    title: 'UDC 2023 Premium Objective Practice',
    level: 'Graduate',
    description: 'Converted from the 2023 UDC objective paper with electricity, magnetism, chemistry and general science questions.',
    duration: 60,
    difficulty: 'Advanced',
    is_free: false,
    bundle_id: 'bfa5c11b-20cf-4f8c-9389-d36f0bf95fb7',
    questions: [
      { id: 'udc-1', section: 'Physics', marks: 1, question_text: 'In India, domestic electricity is supplied at 220 V, while in the USA it is supplied at 110 V. If a 60 W bulb has resistance R in India, what will be the resistance of a comparable 60 W bulb in the USA?', options: ['R', '2R', 'R/2', 'R/4'], correct_option: 'd', explanation: 'At constant power, P = V²/R, so R ∝ V². Halving the voltage to 110 V reduces the resistance to one quarter of the Indian value: R/4.' },
      { id: 'udc-2', section: 'Physics', marks: 1, question_text: 'The line integral of magnetic field over a closed loop is equal to μ₀ times the net current enclosed. This law is called:', options: ['Gauss’s law', 'Ampere’s circuital law', 'Tangent law', 'Maxwell’s law'], correct_option: 'b', explanation: 'Ampere’s circuital law states that the closed-loop integral of magnetic field is proportional to the net enclosed current.' },
      { id: 'udc-3', section: 'Physics', marks: 1, question_text: 'Three equal wire loops, one circular, one semicircular and one square, carry the same current in the same magnetic field. Which one experiences the greatest torque?', options: ['Circle', 'Semi-circle', 'Square', 'All of them equally'], correct_option: 'a', explanation: 'For a given perimeter, the area is maximum for a circle. Since torque depends on area in a uniform field, the circular loop experiences the greatest torque.' },
      { id: 'udc-4', section: 'Physics', marks: 1, question_text: 'Which of the following is NOT true for electromagnetic waves?', options: ['They transport energy', 'They transport momentum', 'They transport angular momentum', 'In vacuum, they travel with different speeds depending on frequency'], correct_option: 'd', explanation: 'Electromagnetic waves all travel at the same speed in vacuum, c, regardless of frequency.' },
      { id: 'udc-5', section: 'Chemistry', marks: 1, question_text: 'The aqueous solutions of sodium formate, anilinium chloride and potassium cyanide are respectively:', options: ['acidic, acidic, basic', 'basic, acidic, basic', 'basic, neutral, basic', 'none of these'], correct_option: 'b', explanation: 'Sodium formate is basic, anilinium chloride is acidic, and potassium cyanide is basic.' },
      { id: 'udc-6', section: 'Chemistry', marks: 1, question_text: 'Among the following cells: Leclanche cell, Nickel-Cadmium cell, Lead storage battery, Mercury cell. Which are primary cells?', options: ['I and IV', 'I and II', 'II and IV', 'II and III'], correct_option: 'a', explanation: 'Leclanche cell and Mercury cell are primary cells; Nickel-Cadmium and lead-acid storage batteries are rechargeable cells.' },
      { id: 'udc-7', section: 'Chemistry', marks: 1, question_text: 'Which pair is correctly matched?', options: ['Emulsion — Smoke', 'Gel — Butter', 'Foam — Mist', 'Whipped Cream — Sol'], correct_option: 'b', explanation: 'Butter is a classic gel, while smoke is a solid aerosol, mist is a liquid aerosol, and whipped cream is a foam.' },
      { id: 'udc-8', section: 'Chemistry', marks: 1, question_text: 'An electrochemical process is used to extract:', options: ['Iron', 'Lead', 'Sodium', 'Silver'], correct_option: 'c', explanation: 'Sodium is extracted industrially by electrolysis of molten sodium chloride (Downs process).' },
      { id: 'udc-9', section: 'General Science', marks: 1, question_text: 'The carbon atoms in diamond are bonded to each other in which geometry?', options: ['Tetrahedral', 'Hexagonal', 'Octahedral', 'None of these'], correct_option: 'a', explanation: 'Each carbon atom in diamond is tetrahedrally bonded to four other carbon atoms.' },
    ],
  },
];

export function getMockTest(id) {
  return mockTests.find((test) => test.id === id) || null;
}

export default mockTests;
