const mockTestCatalog = [
  {
    id: 'class-10',
    title: '10th Pass Govt Exam Mock',
    level: 'Class 10',
    description: 'Build a strong foundation with arithmetic, reasoning, general awareness and English.',
    duration: 20,
    difficulty: 'Foundation',
    questionCount: 8,
    is_free: true,
  },
  {
    id: 'class-12',
    title: '12th Pass Govt Exam Mock',
    level: 'Class 12',
    description: 'Step up your preparation with algebra, data interpretation, reasoning and civics.',
    duration: 25,
    difficulty: 'Intermediate',
    questionCount: 8,
    is_free: true,
  },
  {
    id: 'graduate',
    title: 'Graduate Level',
    level: 'Graduate',
    description: 'Challenge yourself with advanced aptitude, analytical reasoning and Indian polity.',
    duration: 30,
    difficulty: 'Advanced',
    questionCount: 8,
    is_free: true,
  },
  {
    id: 'ldce-asst-2024',
    title: 'LDCE Assistant 2024 Premium Practice',
    level: 'Graduate',
    description: 'Converted from the 2024 LDCE Assistant exam themes: noting, drafting, precis writing, and government-note preparation.',
    duration: 45,
    difficulty: 'Advanced',
    questionCount: 8,
    is_free: false,
    bundle_id: 'f90e203c-5bb6-460f-989a-6f2d8ab103d6',
  },
  {
    id: 'udc-2023',
    title: 'UDC 2023 Premium Objective Practice',
    level: 'Graduate',
    description: 'Converted from the 2023 UDC objective paper with physics, chemistry, economics and general science questions.',
    duration: 60,
    difficulty: 'Advanced',
    questionCount: 9,
    is_free: false,
    bundle_id: 'bfa5c11b-20cf-4f8c-9389-d36f0bf95fb7',
  },
];

export default mockTestCatalog;
